name: Release

on:
  push:
    branches:
      - main

env:
  NODE_VERSION: 18.10.0
  PNPM_VERSION: 8
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

jobs:
  release:
    name: Release
    if: contains(github.event.head_commit.message, 'RELEASE')
    runs-on: ubuntu-latest
    steps:
      - name: Get token
        id: get_token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2
        with:
          private_key: ${{ secrets.RELEASE_APP_PEM }}
          app_id: ${{ secrets.RELEASE_APP_ID }}
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          # persist-credentials: false
          token: ${{ steps.get_token.outputs.token }}
          ref: ${{ github.ref }}
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://registry.npmjs.org/
      - uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
      - name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts
        env:
          CI: true
      - name: Build
        run: npm run version:ci
        env:
          CI: true
          GITHUB_TOKEN: ${{ steps.get_token.outputs.token }}
      - name: Run pnpm publish
        run: pnpm -r publish --access=public --no-git-checks
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.CI_NPM_REGISTRY }}
      - name: Push versions, changelog and tags
        run: git push --atomic origin main $(git tag -l)
        env:
          CI: true
          GITHUB_TOKEN: ${{ steps.get_token.outputs.token }}
