name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    if: "contains(github.event.head_commit.message, 'RELEASE')"
    runs-on: ubuntu-latest
    steps:
      - name: Get token
        id: get_token
        uses: tibdex/github-app-token@v1
        with:
          private_key: ${{ secrets.RELEASE_APP_PEM }}
          app_id: ${{ secrets.RELEASE_APP_ID }}
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # persist-credentials: false
          token: ${{ steps.get_token.outputs.token }}
          ref: ${{ github.ref }}
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://registry.npmjs.org/
      - uses: pnpm/action-setup@v2
        with:
          version: 7.28.0
      - name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts
        env:
          CI: true
      - name: Build
        run: npm run version:ci
        env:
          CI: true
          GITHUB_TOKEN: ${{ steps.get_token.outputs.token }}
      - name: Run pnpm publish
        run: pnpm -r publish --access=public --no-git-checks
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.CI_NPM_REGISTRY }}
      - name: Push versions, changelog and tags
        run: git push --atomic origin main $(git tag -l)
        env:
          CI: true
          GITHUB_TOKEN: ${{ steps.get_token.outputs.token }}
