name: 👊 Bump Version & Release

on:
  push:
    branches:
      - nx

jobs:
  release:
    name: Release
    if: "contains(github.event.head_commit.message, 'DUMMY')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://npm.pkg.github.com/
      - uses: pnpm/action-setup@v2
        with:
          version: 7.28.0
      - name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: npm run version:ci
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Update pnpm workspace yaml
        run: sed -i.bu 's/packages\//dist\/packages\//' ./pnpm-workspace.yaml
      - name: Run pnpm install
        run: pnpm install --no-frozen-lockfile
      - name: Run pnpm publish
        run: pnpm -r publish --no-git-checks
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Push tags
        run: git push --tags
